from general import *
from ntp import *
from messenger import *
import unittest

'''
ntp == 10.20.30.40
msg_server == 1.1.1.1
msg_replic_1 == 1.1.2.1
msg_replic_2 == 1.1.2.2
comp1 == 172.10.1.1
comp2 == 172.10.1.2
'''

class TestMessenger(unittest.TestCase):
    def test_environment(self):
        ntp_serv_daemon = NTPServer()
        ntp_serv = Computer()
        ntp_serv.get_service(ntp_serv_daemon)
        ntp_serv_daemon.set_host(ntp_serv)

        msg_server_daemon = MSGServer()
        msg_server = Computer()
        msg_server.get_service(msg_server_daemon)
        msg_server_daemon.set_host(msg_server)
        msg_server_timer = Timer()
        msg_server.get_service(msg_server_timer)
        msg_server_timer.set_host(msg_server)

        msg_server_rep1_daemon = MSGServerReplic()
        msg_server_rep1 = Computer()
        msg_server_rep1.get_service(msg_server_rep1_daemon)
        msg_server_rep1_daemon.set_host(msg_server_rep1)
        msg_server_rep1_timer = Timer()
        msg_server_rep1.get_service(msg_server_rep1_timer)
        msg_server_rep1_timer.set_host(msg_server_rep1)

        msg_server_rep2_daemon = MSGServerReplic()
        msg_server_rep2 = Computer()
        msg_server_rep2.get_service(msg_server_rep2_daemon)
        msg_server_rep2_daemon.set_host(msg_server_rep2)
        msg_server_rep2_timer = Timer()
        msg_server_rep2.get_service(msg_server_rep2_timer)
        msg_server_rep2_timer.set_host(msg_server_rep2)

        messenger1 = Messenger()
        messenger2 = Messenger()
        messenger1.set_msg_server("1.1.1.1")
        messenger2.set_msg_server("1.1.1.1")
        comp1 = Computer()
        comp2 = Computer()
        comp1.get_service(messenger1)
        comp2.get_service(messenger2)
        comp1_timer = Timer()
        comp2_timer = Timer()
        comp1.get_service(comp1_timer)
        comp2.get_service(comp2_timer)
        comp1_timer.set_host(comp1)
        comp2_timer.set_host(comp2)

        net = Network()
        net.add_host(ntp_serv, "10.20.30.40")
        net.add_host(msg_server, "1.1.1.1")
        net.add_host(msg_server_rep1, "1.1.2.1")
        net.add_host(msg_server_rep2, "1.1.2.2")
        net.add_host(comp1, "172.10.1.1")
        net.add_host(comp2, "172.10.1.2")

        net.set_ntp("10.20.30.40")
        msg_server_daemon.add_replic(msg_server_rep1_daemon)
        msg_server_daemon.add_replic(msg_server_rep2_daemon)

    def test_send_msg(self):
        ntp_serv_daemon = NTPServer()
        ntp_serv = Computer()
        ntp_serv.get_service(ntp_serv_daemon)
        ntp_serv_daemon.set_host(ntp_serv)

        msg_server_daemon = MSGServer()
        msg_server = Computer()
        msg_server.get_service(msg_server_daemon)
        msg_server_daemon.set_host(msg_server)
        msg_server_timer = Timer()
        msg_server.get_service(msg_server_timer)
        msg_server_timer.set_host(msg_server)

        msg_server_rep1_daemon = MSGServerReplic()
        msg_server_rep1 = Computer()
        msg_server_rep1.get_service(msg_server_rep1_daemon)
        msg_server_rep1_daemon.set_host(msg_server_rep1)
        msg_server_rep1_timer = Timer()
        msg_server_rep1.get_service(msg_server_rep1_timer)
        msg_server_rep1_timer.set_host(msg_server_rep1)

        msg_server_rep2_daemon = MSGServerReplic()
        msg_server_rep2 = Computer()
        msg_server_rep2.get_service(msg_server_rep2_daemon)
        msg_server_rep2_daemon.set_host(msg_server_rep2)
        msg_server_rep2_timer = Timer()
        msg_server_rep2.get_service(msg_server_rep2_timer)
        msg_server_rep2_timer.set_host(msg_server_rep2)

        messenger1 = Messenger()
        messenger2 = Messenger()
        messenger1.set_msg_server("1.1.1.1")
        messenger2.set_msg_server("1.1.1.1")
        comp1 = Computer()
        comp2 = Computer()
        comp1.get_service(messenger1)
        comp2.get_service(messenger2)
        messenger1.set_host(comp1)
        messenger2.set_host(comp2)
        comp1_timer = Timer()
        comp2_timer = Timer()
        comp1.get_service(comp1_timer)
        comp2.get_service(comp2_timer)
        comp1_timer.set_host(comp1)
        comp2_timer.set_host(comp2)

        net = Network()
        net.add_host(ntp_serv, "10.20.30.40")
        net.add_host(msg_server, "1.1.1.1")
        net.add_host(msg_server_rep1, "1.1.2.1")
        net.add_host(msg_server_rep2, "1.1.2.2")
        net.add_host(comp1, "172.10.1.1")
        net.add_host(comp2, "172.10.1.2")

        net.set_ntp("10.20.30.40")
        msg_server_daemon.add_replic(msg_server_rep1_daemon)
        msg_server_daemon.add_replic(msg_server_rep2_daemon)

        comp1.services["Messenger"].send_msg("172.10.1.2", "Hello")
        result = comp2.services["Messenger"].db.get_messages_num()
        self.assertEqual(result, 1)

    def test_send_msg_and_read_last_msg(self):
        ntp_serv_daemon = NTPServer()
        ntp_serv = Computer()
        ntp_serv.get_service(ntp_serv_daemon)
        ntp_serv_daemon.set_host(ntp_serv)

        msg_server_daemon = MSGServer()
        msg_server = Computer()
        msg_server.get_service(msg_server_daemon)
        msg_server_daemon.set_host(msg_server)
        msg_server_timer = Timer()
        msg_server.get_service(msg_server_timer)
        msg_server_timer.set_host(msg_server)

        msg_server_rep1_daemon = MSGServerReplic()
        msg_server_rep1 = Computer()
        msg_server_rep1.get_service(msg_server_rep1_daemon)
        msg_server_rep1_daemon.set_host(msg_server_rep1)
        msg_server_rep1_timer = Timer()
        msg_server_rep1.get_service(msg_server_rep1_timer)
        msg_server_rep1_timer.set_host(msg_server_rep1)

        msg_server_rep2_daemon = MSGServerReplic()
        msg_server_rep2 = Computer()
        msg_server_rep2.get_service(msg_server_rep2_daemon)
        msg_server_rep2_daemon.set_host(msg_server_rep2)
        msg_server_rep2_timer = Timer()
        msg_server_rep2.get_service(msg_server_rep2_timer)
        msg_server_rep2_timer.set_host(msg_server_rep2)

        messenger1 = Messenger()
        messenger2 = Messenger()
        messenger1.set_msg_server("1.1.1.1")
        messenger2.set_msg_server("1.1.1.1")
        comp1 = Computer()
        comp2 = Computer()
        comp1.get_service(messenger1)
        comp2.get_service(messenger2)
        messenger1.set_host(comp1)
        messenger2.set_host(comp2)
        comp1_timer = Timer()
        comp2_timer = Timer()
        comp1.get_service(comp1_timer)
        comp2.get_service(comp2_timer)
        comp1_timer.set_host(comp1)
        comp2_timer.set_host(comp2)

        net = Network()
        net.add_host(ntp_serv, "10.20.30.40")
        net.add_host(msg_server, "1.1.1.1")
        net.add_host(msg_server_rep1, "1.1.2.1")
        net.add_host(msg_server_rep2, "1.1.2.2")
        net.add_host(comp1, "172.10.1.1")
        net.add_host(comp2, "172.10.1.2")

        net.set_ntp("10.20.30.40")
        msg_server_daemon.add_replic(msg_server_rep1_daemon)
        msg_server_daemon.add_replic(msg_server_rep2_daemon)

        comp1.services["Messenger"].send_msg("172.10.1.2", "Hello")
        result = comp2.services["Messenger"].db.db[comp2.services["Messenger"].db.get_messages_num()-1].get_msg()
        self.assertEqual(result, "Hello")

    def test_send_msg_and_download_history(self):
        ntp_serv_daemon = NTPServer()
        ntp_serv = Computer()
        ntp_serv.get_service(ntp_serv_daemon)
        ntp_serv_daemon.set_host(ntp_serv)

        msg_server_daemon = MSGServer()
        msg_server = Computer()
        msg_server.get_service(msg_server_daemon)
        msg_server_daemon.set_host(msg_server)
        msg_server_timer = Timer()
        msg_server.get_service(msg_server_timer)
        msg_server_timer.set_host(msg_server)

        msg_server_rep1_daemon = MSGServerReplic()
        msg_server_rep1 = Computer()
        msg_server_rep1.get_service(msg_server_rep1_daemon)
        msg_server_rep1_daemon.set_host(msg_server_rep1)
        msg_server_rep1_timer = Timer()
        msg_server_rep1.get_service(msg_server_rep1_timer)
        msg_server_rep1_timer.set_host(msg_server_rep1)

        msg_server_rep2_daemon = MSGServerReplic()
        msg_server_rep2 = Computer()
        msg_server_rep2.get_service(msg_server_rep2_daemon)
        msg_server_rep2_daemon.set_host(msg_server_rep2)
        msg_server_rep2_timer = Timer()
        msg_server_rep2.get_service(msg_server_rep2_timer)
        msg_server_rep2_timer.set_host(msg_server_rep2)

        messenger1 = Messenger()
        messenger2 = Messenger()
        messenger1.set_msg_server("1.1.1.1")
        messenger2.set_msg_server("1.1.1.1")
        comp1 = Computer()
        comp2 = Computer()
        comp1.get_service(messenger1)
        comp2.get_service(messenger2)
        messenger1.set_host(comp1)
        messenger2.set_host(comp2)
        comp1_timer = Timer()
        comp2_timer = Timer()
        comp1.get_service(comp1_timer)
        comp2.get_service(comp2_timer)
        comp1_timer.set_host(comp1)
        comp2_timer.set_host(comp2)

        net = Network()
        net.add_host(ntp_serv, "10.20.30.40")
        net.add_host(msg_server, "1.1.1.1")
        net.add_host(msg_server_rep1, "1.1.2.1")
        net.add_host(msg_server_rep2, "1.1.2.2")
        net.add_host(comp1, "172.10.1.1")
        net.add_host(comp2, "172.10.1.2")

        net.set_ntp("10.20.30.40")
        msg_server_daemon.add_replic(msg_server_rep1_daemon)
        msg_server_daemon.add_replic(msg_server_rep2_daemon)

        comp1.services["Messenger"].send_msg("172.10.1.2", "Hello")
        comp1.services["Messenger"].download_history()
        result = comp1.services["Messenger"].history.get_messages_num()
        self.assertEqual(result, 1)

    def test_send_msg_and_download_history_without_replic(self):
        ntp_serv_daemon = NTPServer()
        ntp_serv = Computer()
        ntp_serv.get_service(ntp_serv_daemon)
        ntp_serv_daemon.set_host(ntp_serv)

        msg_server_daemon = MSGServer()
        msg_server = Computer()
        msg_server.get_service(msg_server_daemon)
        msg_server_daemon.set_host(msg_server)
        msg_server_timer = Timer()
        msg_server.get_service(msg_server_timer)
        msg_server_timer.set_host(msg_server)

        messenger1 = Messenger()
        messenger2 = Messenger()
        messenger1.set_msg_server("1.1.1.1")
        messenger2.set_msg_server("1.1.1.1")
        comp1 = Computer()
        comp2 = Computer()
        comp1.get_service(messenger1)
        comp2.get_service(messenger2)
        messenger1.set_host(comp1)
        messenger2.set_host(comp2)
        comp1_timer = Timer()
        comp2_timer = Timer()
        comp1.get_service(comp1_timer)
        comp2.get_service(comp2_timer)
        comp1_timer.set_host(comp1)
        comp2_timer.set_host(comp2)

        net = Network()
        net.add_host(ntp_serv, "10.20.30.40")
        net.add_host(msg_server, "1.1.1.1")
        net.add_host(comp1, "172.10.1.1")
        net.add_host(comp2, "172.10.1.2")

        net.set_ntp("10.20.30.40")

        comp1.services["Messenger"].send_msg("172.10.1.2", "Hello")
        comp1.services["Messenger"].download_history()
        result = comp1.services["Messenger"].history.get_messages_num()
        self.assertEqual(result, 1)

    def test_send_msg_and_download_history_broken_replic(self):
        ntp_serv_daemon = NTPServer()
        ntp_serv = Computer()
        ntp_serv.get_service(ntp_serv_daemon)
        ntp_serv_daemon.set_host(ntp_serv)

        msg_server_daemon = MSGServer()
        msg_server = Computer()
        msg_server.get_service(msg_server_daemon)
        msg_server_daemon.set_host(msg_server)
        msg_server_timer = Timer()
        msg_server.get_service(msg_server_timer)
        msg_server_timer.set_host(msg_server)

        msg_server_rep1_daemon = MSGServerReplic()
        msg_server_rep1 = Computer()
        msg_server_rep1.get_service(msg_server_rep1_daemon)
        msg_server_rep1_daemon.set_host(msg_server_rep1)
        msg_server_rep1_timer = Timer()
        msg_server_rep1.get_service(msg_server_rep1_timer)
        msg_server_rep1_timer.set_host(msg_server_rep1)

        msg_server_rep2_daemon = MSGServerReplic()
        msg_server_rep2 = Computer()
        msg_server_rep2.get_service(msg_server_rep2_daemon)
        msg_server_rep2_daemon.set_host(msg_server_rep2)
        msg_server_rep2_timer = Timer()
        msg_server_rep2.get_service(msg_server_rep2_timer)
        msg_server_rep2_timer.set_host(msg_server_rep2)

        messenger1 = Messenger()
        messenger2 = Messenger()
        messenger1.set_msg_server("1.1.1.1")
        messenger2.set_msg_server("1.1.1.1")
        comp1 = Computer()
        comp2 = Computer()
        comp1.get_service(messenger1)
        comp2.get_service(messenger2)
        messenger1.set_host(comp1)
        messenger2.set_host(comp2)
        comp1_timer = Timer()
        comp2_timer = Timer()
        comp1.get_service(comp1_timer)
        comp2.get_service(comp2_timer)
        comp1_timer.set_host(comp1)
        comp2_timer.set_host(comp2)

        net = Network()
        net.add_host(ntp_serv, "10.20.30.40")
        net.add_host(msg_server, "1.1.1.1")
        net.add_host(msg_server_rep1, "1.1.2.1")
        net.add_host(msg_server_rep2, "1.1.2.2")
        net.add_host(comp1, "172.10.1.1")
        net.add_host(comp2, "172.10.1.2")

        net.set_ntp("10.20.30.40")
        msg_server_daemon.add_replic(msg_server_rep1_daemon)
        msg_server_daemon.add_replic(msg_server_rep2_daemon)

        comp1.services["Messenger"].send_msg("172.10.1.2", "Hello")
        net.delete_host("1.1.2.1")
        net.delete_host("1.1.2.2")
        comp1.services["Messenger"].download_history()
        result = comp1.services["Messenger"].history.get_messages_num()
        self.assertEqual(result, 1)

if __name__ == '__main__':
    unittest.main()
